/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.nanojaw.sudoku_app.backend;

public class backend {
  public static String GenerateSudoku() {
    return backendJNI.GenerateSudoku();
  }

  public static String GenerateHexSudoku() {
    return backendJNI.GenerateHexSudoku();
  }

  public static void Free(Sudokutype type) {
    backendJNI.Free(type.swigValue());
  }

  public static String LoadSudoku() {
    return backendJNI.LoadSudoku();
  }

  public static String LoadHexSudoku() {
    return backendJNI.LoadHexSudoku();
  }

  public static void SaveSudoku() {
    backendJNI.SaveSudoku();
  }

  public static void SaveHexSudoku() {
    backendJNI.SaveHexSudoku();
  }

}
