/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.nanojaw.sudoku_app.backend;

public class backendJNI {
  public final static native String GenerateSudoku();
  public final static native String GenerateHexSudoku();
  public final static native void Free(int jarg1);
  public final static native String LoadSudoku();
  public final static native String LoadHexSudoku();
  public final static native void SaveSudoku();
  public final static native void SaveHexSudoku();
}
